import{a as L,S as b,i as v}from"./assets/vendor-DXaqCXe3.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const w="49301647-30570283b511de5f9e60954e8",S="https://pixabay.com/api/",q=15;async function m(t,s=1){try{return(await L.get(S,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:q,page:s}})).data.hits}catch(r){return console.error("Error fetching images:",r),[]}}const f=document.querySelector(".gallery");let E=new b(".gallery a",{captionsData:"alt",captionDelay:250});function h(t,s=!1){s||(f.innerHTML=""),f.insertAdjacentHTML("beforeend",t.map(({webformatURL:r,largeImageURL:i,tags:e,likes:o,views:n,comments:p,downloads:y})=>`
        <li class="gallery-item">
            <a href="${i}">
                <img src="${r}" alt="${e}" loading="lazy" />
            </a>
            <div class="info">
                <p>❤️ ${o} Likes</p>
                <p>👁️ ${n} Views</p>
                <p>💬 ${p} Comments</p>
                <p>⬇️ ${y} Downloads</p>
            </div>
        </li>
      `).join("")),E.refresh()}function g(){document.querySelector(".loader").classList.add("visible")}function l(){document.querySelector(".loader").classList.remove("visible")}function d(t){v.error({title:"Error",message:t,position:"topRight"})}document.querySelector(".form").addEventListener("submit",async t=>{t.preventDefault();const s=t.target.elements["search-text"].value.trim();if(!s){d("Please enter a search term!");return}g(),u=s,a=1,c.classList.add("hidden");const r=await m(u,a);l(),r.length===0?d("Sorry, there are no images matching your search query. Please try again!"):(h(r),r.length===15&&c.classList.remove("hidden"))});let a=1,u="";const c=document.querySelector(".load-more");c.addEventListener("click",async()=>{a+=1,g();try{const t=await m(u,a);if(l(),t.length===0){console.log("Більше зображень немає!"),c.classList.add("hidden"),d("We're sorry, but you've reached the end of search results.");return}h(t,!0);const s=t.length;a*15>=s&&(console.log("🔚 Кінець колекції! Ховаємо кнопку."),c.classList.add("hidden"));const r=document.querySelector(".gallery-item");if(r){const i=r.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}}catch(t){console.error("Помилка під час отримання даних:",t),l()}});
//# sourceMappingURL=index.js.map
