import{a as L,S as b,i as v}from"./assets/vendor-DXaqCXe3.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const w="49301647-30570283b511de5f9e60954e8",P="https://pixabay.com/api/",S=15;async function m(r,s=1){try{const t=await L.get(P,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:s}});return console.log("📸 API Response:",t.data),{images:t.data.hits,totalHits:t.data.totalHits}}catch(t){return console.error("Error fetching images:",t),{images:[],totalHits:0}}}const f=document.querySelector(".gallery");let q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function h(r,s=!1){s||(f.innerHTML=""),f.insertAdjacentHTML("beforeend",r.map(({webformatURL:t,largeImageURL:i,tags:e,likes:o,views:n,comments:p,downloads:y})=>`
        <li class="gallery-item">
            <a href="${i}">
                <img src="${t}" alt="${e}" loading="lazy" />
            </a>
            <div class="info">
                <p>❤️ ${o} Likes</p>
                <p>👁️ ${n} Views</p>
                <p>💬 ${p} Comments</p>
                <p>⬇️ ${y} Downloads</p>
            </div>
        </li>
      `).join("")),q.refresh()}function g(){document.querySelector(".loader").classList.add("visible")}function d(){document.querySelector(".loader").classList.remove("visible")}function l(r){v.error({title:"Error",message:r,position:"topRight"})}document.querySelector(".form").addEventListener("submit",async r=>{r.preventDefault();const s=r.target.elements["search-text"].value.trim();if(!s){l("Please enter a search term!");return}g(),u=s,a=1,c.classList.add("hidden");const{images:t,totalHits:i}=await m(u,a);d(),t.length===0?l("Sorry, there are no images matching your search query. Please try again!"):(h(t),a*15<i&&c.classList.remove("hidden"))});let a=1,u="";const c=document.querySelector(".load-more");c.addEventListener("click",async()=>{a+=1,g();try{const{images:r,totalHits:s}=await m(u,a);if(d(),r.length===0){console.log("Більше зображень немає!"),c.classList.add("hidden"),l("We're sorry, but you've reached the end of search results.");return}h(r,!0),a*15>=s&&(console.log("🔚 Кінець колекції! Ховаємо кнопку."),c.classList.add("hidden"),l("We're sorry, but you've reached the end of search results."));const t=document.querySelector(".gallery-item");if(t){const i=t.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}}catch(r){console.error("Помилка під час отримання даних:",r),d()}});
//# sourceMappingURL=index.js.map
