import{a as L,S as b,i as v}from"./assets/vendor-DXaqCXe3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const w="49301647-30570283b511de5f9e60954e8",S="https://pixabay.com/api/",q=15;async function f(r,t=1){try{return(await L.get(S,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:q,page:t}})).data.hits}catch(s){return console.error("Error fetching images:",s),[]}}const u=document.querySelector(".gallery");let E=new b(".gallery a",{captionsData:"alt",captionDelay:250});function m(r,t=!1){t||(u.innerHTML=""),u.insertAdjacentHTML("beforeend",r.map(({webformatURL:s,largeImageURL:n,tags:e,likes:o,views:i,comments:g,downloads:y})=>`
        <li class="gallery-item">
            <a href="${n}">
                <img src="${s}" alt="${e}" loading="lazy" />
            </a>
            <div class="info">
                <p>❤️ ${o} Likes</p>
                <p>👁️ ${i} Views</p>
                <p>💬 ${g} Comments</p>
                <p>⬇️ ${y} Downloads</p>
            </div>
        </li>
      `).join("")),E.refresh()}function h(){document.querySelector(".loader").classList.add("visible")}function p(){document.querySelector(".loader").classList.remove("visible")}function l(r){v.error({title:"Error",message:r,position:"topRight"})}document.querySelector(".form").addEventListener("submit",async r=>{r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(!t){l("Please enter a search term!");return}h(),d=t,a=1,c.classList.add("hidden");const s=await f(d,a);p(),s.length===0?l("Sorry, there are no images matching your search query. Please try again!"):(m(s),s.length===15&&c.classList.remove("hidden"))});let a=1,d="";const c=document.querySelector(".load-more");c.addEventListener("click",async()=>{a+=1,h();try{const r=await f(d,a);if(r.length===0){console.log("Більше зображень немає!"),c.classList.add("hidden"),l("We're sorry, but you've reached the end of search results.");return}m(r,!0);const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}catch(r){console.error("Помилка під час отримання даних:",r)}finally{p()}});
//# sourceMappingURL=index.js.map
